CPP = gcc

cfiles.o: main.c common.c led.c digits.c faces.c fullfillment.c securityProtocol.c sensor.c servo.c utilities.c
	$(CPP) -c main.c common.c led.c digits.c faces.c fullfillment.c securityProtocol.c sensor.c servo.c utilities.c

# common.o: common.c
# 	$(CPP) -c common.c

# digits.o: digits.c
# 	$(CPP) -c digits.c

# faces.o: faces.c
# 	$(CPP) -c faces.c

# fullfillment.o: fullfillment.c
# 	$(CPP) -c fullfillment.c

# led.o: led.c
# 	$(CPP) -c led.c

# securityProtocol.o: securityProtocol.c
# 	$(CPP) -c securityProtocol.c

# sensor.o: sensor.c
# 	$(CPP) -c sensor.c

# servo.o: servo.c
# 	$(CPP) -c servo.c

# utilities.o: utilities.c
# 	$(CPP) -c utilities.c

make clean:
	rm -f *.o